In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Dataset.csv")
df = df.sample(frac = 0.5)
print(df.shape)

(13440, 57)


In [ ]:
df.head()

Unnamed: 0   coeff_var  fractal_dimension  ...  arousal  dominance  liking
8881           19 -653.237235           1.964181  ...     6.31       2.38    7.81
6980            8   72.215513           1.991463  ...     4.09       4.86    6.15
18773          20   51.080333           1.997740  ...     6.03       9.00    6.83
7138           19    5.678293           1.990888  ...     5.71       5.77    5.99
5543           20  -48.459438           1.983340  ...     5.38       1.53    5.99

[5 rows x 57 columns]

In [ ]:
df.shape

(13440, 57)

In [ ]:
df = df.replace([np.inf, -np.inf], np.nan)
df.head()

Unnamed: 0   coeff_var  fractal_dimension  ...  arousal  dominance  liking
8881           19 -653.237235           1.964181  ...     6.31       2.38    7.81
6980            8   72.215513           1.991463  ...     4.09       4.86    6.15
18773          20   51.080333           1.997740  ...     6.03       9.00    6.83
7138           19    5.678293           1.990888  ...     5.71       5.77    5.99
5543           20  -48.459438           1.983340  ...     5.38       1.53    5.99

[5 rows x 57 columns]

In [ ]:
df = df.replace([np.inf, -np.inf], np.nan).dropna(subset=["coeff_var"], how="all")
df.shape

(13067, 57)

In [ ]:
df.isnull().values.any()

False

In [ ]:
df['dominance']

8881     2.38
6980     4.86
18773    9.00
7138     5.77
5543     1.53
         ... 
15244    8.06
20120    2.97
22062    6.03
15084    9.00
23279    3.71
Name: dominance, Length: 13067, dtype: float64

In [ ]:
df['dominance'] = np.where(df['dominance']<=4.90 , 0, df['dominance'])
df['dominance'] = np.where(df['dominance']>4.90 , 1, df['dominance'])
df['valence'] = np.where(df['valence']<=4.90 , 0, df['valence'])
df['valence'] = np.where(df['valence']>4.90 , 1, df['valence'])
df['arousal'] = np.where(df['arousal']<=4.90 , 0, df['arousal'])
df['arousal'] = np.where(df['arousal']>4.90 , 1, df['arousal'])
df['liking'] = np.where(df['liking']<=4.90 , 0, df['liking'])
df['liking'] = np.where(df['liking']>4.90 , 1, df['liking'])


In [ ]:
df['dominance'].unique()

array([0., 1.])

In [ ]:
df.head()

Unnamed: 0   coeff_var  fractal_dimension  ...  arousal  dominance  liking
8881           19 -653.237235           1.964181  ...      1.0        0.0     1.0
6980            8   72.215513           1.991463  ...      0.0        0.0     1.0
18773          20   51.080333           1.997740  ...      1.0        1.0     1.0
7138           19    5.678293           1.990888  ...      1.0        1.0     1.0
5543           20  -48.459438           1.983340  ...      1.0        0.0     1.0

[5 rows x 57 columns]

In [ ]:
df.shape

(13067, 57)

## Choosing my X and Y

In [ ]:
X = df.drop(['valence','liking','dominance','arousal'],axis = 1)
X.head()

Unnamed: 0   coeff_var  ...  Entropy_A_min  Entropy_A_max
8881           19 -653.237235  ...   11338.150744   4.976220e+06
6980            8   72.215513  ...   59010.240385   6.130247e+06
18773          20   51.080333  ...   18411.365526   5.510635e+06
7138           19    5.678293  ...   16805.100603   3.156649e+06
5543           20  -48.459438  ...   26252.581305   2.416832e+05

[5 rows x 53 columns]

In [ ]:
X = X.drop(['Unnamed: 0'],axis = 1)
X.head()

coeff_var  fractal_dimension  ...  Entropy_A_min  Entropy_A_max
8881  -653.237235           1.964181  ...   11338.150744   4.976220e+06
6980    72.215513           1.991463  ...   59010.240385   6.130247e+06
18773   51.080333           1.997740  ...   18411.365526   5.510635e+06
7138     5.678293           1.990888  ...   16805.100603   3.156649e+06
5543   -48.459438           1.983340  ...   26252.581305   2.416832e+05

[5 rows x 52 columns]

In [ ]:
df = df.drop(["Unnamed: 0"],axis = 1)
df.head()

coeff_var  fractal_dimension  kurtosis  ...  arousal  dominance  liking
8881  -653.237235           1.964181  2.400335  ...      1.0        0.0     1.0
6980    72.215513           1.991463  0.146082  ...      0.0        0.0     1.0
18773   51.080333           1.997740  1.930806  ...      1.0        1.0     1.0
7138     5.678293           1.990888  0.080560  ...      1.0        1.0     1.0
5543   -48.459438           1.983340  0.216440  ...      1.0        0.0     1.0

[5 rows x 56 columns]

In [ ]:
# Y consists of all 4 labels while small y consists of only one output label
Y = df[['valence','arousal','liking','dominance']]
Y.head()

valence  arousal  liking  dominance
8881       0.0      1.0     1.0        0.0
6980       1.0      0.0     1.0        0.0
18773      1.0      1.0     1.0        1.0
7138       1.0      1.0     1.0        1.0
5543       0.0      1.0     1.0        0.0

In [ ]:
y = df['valence']
y[0:5]

8881     0.0
6980     1.0
18773    1.0
7138     1.0
5543     0.0
Name: valence, dtype: float64

In [ ]:
# converting y to np array and flattening using ravel
y = np.array(y)
y = y.ravel()
y[0:5]

array([0., 1., 1., 1., 0.])

In [ ]:
print(X.shape)
print(y.shape)

(13067, 52)
(13067,)


### For generating dataframe with specific input columns

In [ ]:
def select_columns(data_frame, column_names):
    new_frame = data_frame.loc[:, column_names]
    return new_frame

# Building Model using Random Forest

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
def run_model(X,y):
        print(X.shape,y.shape)
        from sklearn.ensemble import RandomForestClassifier
        model = RandomForestClassifier()
        X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33,random_state = 42)
        model.fit(X_train,y_train)
        return model.score(X_test,y_test)

## Before feature selection 

In [ ]:
run_model(X,y)  # accuracy - 64.34%

(13067, 52) (13067,)


0.6434036633433805

In [ ]:
X.head()

coeff_var  fractal_dimension  ...  Entropy_A_min  Entropy_A_max
8881  -653.237235           1.964181  ...   11338.150744   4.976220e+06
6980    72.215513           1.991463  ...   59010.240385   6.130247e+06
18773   51.080333           1.997740  ...   18411.365526   5.510635e+06
7138     5.678293           1.990888  ...   16805.100603   3.156649e+06
5543   -48.459438           1.983340  ...   26252.581305   2.416832e+05

[5 rows x 52 columns]

In [ ]:
df.head()

coeff_var  fractal_dimension  kurtosis  ...  arousal  dominance  liking
8881  -653.237235           1.964181  2.400335  ...      1.0        0.0     1.0
6980    72.215513           1.991463  0.146082  ...      0.0        0.0     1.0
18773   51.080333           1.997740  1.930806  ...      1.0        1.0     1.0
7138     5.678293           1.990888  0.080560  ...      1.0        1.0     1.0
5543   -48.459438           1.983340  0.216440  ...      1.0        0.0     1.0

[5 rows x 56 columns]

# Feature Selection Techniques

## 1. Borurta

In [ ]:
X_shadow = X.apply(np.random.permutation)
X_shadow.columns = ['shadow_' + feat for feat in X.columns]
### make X_boruta by appending X_shadow to X
X_boruta = pd.concat([X, X_shadow], axis = 1)

In [ ]:
X_boruta.head()

coeff_var  ...  shadow_Entropy_A_max
8881  -653.237235  ...          1.299281e+06
6980    72.215513  ...          3.692609e+07
18773   51.080333  ...          6.607023e+06
7138     5.678293  ...          3.182933e+04
5543   -48.459438  ...          3.644058e+06

[5 rows x 104 columns]

In [ ]:
from sklearn.ensemble import RandomForestClassifier
### fit a random forest (suggested max_depth between 3 and 7)
forest = RandomForestClassifier(max_depth = 5, random_state = 42)
forest.fit(X_boruta, y)
### store feature importances
feat_imp_X = forest.feature_importances_[:len(df.columns)]
feat_imp_shadow = forest.feature_importances_[len(df.columns):]
### compute hits
hits = feat_imp_X > feat_imp_shadow.max()

In [ ]:
feat_imp_X

array([0.00295545, 0.02097309, 0.01091367, 0.0253831 , 0.01197288,
       0.01316471, 0.03841999, 0.01058422, 0.00533018, 0.01021523,
       0.00692996, 0.02672182, 0.00788731, 0.01040572, 0.04991303,
       0.02889015, 0.01458701, 0.01282052, 0.01028453, 0.0127427 ,
       0.00863093, 0.0051834 , 0.0090917 , 0.01216425, 0.00397577,
       0.00919925, 0.01377557, 0.01833036, 0.        , 0.04152306,
       0.01954004, 0.00756716, 0.00835549, 0.01211534, 0.00585881,
       0.00986668, 0.01489549, 0.        , 0.00571085, 0.00375055,
       0.02457533, 0.0185335 , 0.01417567, 0.02549329, 0.02504823,
       0.02115192, 0.02815236, 0.01846713, 0.01742191, 0.0106718 ,
       0.00859111, 0.01202758, 0.00448845, 0.00338791, 0.00423396,
       0.00629743])

In [ ]:
feat_imp_shadow

array([0.00398593, 0.00414241, 0.00465764, 0.00522873, 0.0049076 ,
       0.00766362, 0.00370523, 0.00295307, 0.00650539, 0.00515183,
       0.00311683, 0.00570207, 0.00223863, 0.00341037, 0.00408584,
       0.00467828, 0.00495246, 0.00544017, 0.00477059, 0.00349402,
       0.00278296, 0.00708458, 0.00467312, 0.00275269, 0.        ,
       0.00420443, 0.00317053, 0.00618726, 0.00485439, 0.00455121,
       0.00321185, 0.00606717, 0.00601427, 0.        , 0.0058264 ,
       0.00653074, 0.00216461, 0.00298772, 0.00490513, 0.00561525,
       0.00853554, 0.00476848, 0.00213812, 0.00781002, 0.0052928 ,
       0.00402545, 0.00477662, 0.00493038])

In [ ]:
hits # after one run -> true means that the corresponding features has surpassed the threshold and is a good feature

array([False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True,  True,
        True, False,  True,  True, False, False,  True, False,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False])

In [ ]:
# for 5 iteration
### initialize hits counter
hits = np.zeros((len(X.columns)))
### repeat 20 times
for iter_ in range(30):
   ### make X_shadow by randomly permuting each column of X
   np.random.seed(iter_)
   X_shadow = X.apply(np.random.permutation)
   X_boruta = pd.concat([X, X_shadow], axis = 1)
   ### fit a random forest (suggested max_depth between 3 and 7)
   forest = RandomForestClassifier(max_depth = 5, random_state = 42)
   forest.fit(X_boruta, y)
   ### store feature importance
   feat_imp_X = forest.feature_importances_[:len(X.columns)]
   feat_imp_shadow = forest.feature_importances_[len(X.columns):]
   ### compute hits for this trial and add to counter
   hits += (feat_imp_X > feat_imp_shadow.max())

In [ ]:
hits

array([ 0., 30., 30., 30., 30., 28., 30., 30.,  2., 30., 17., 30., 10.,
       22., 30., 30., 30., 26., 27., 30., 25.,  1.,  9., 30.,  0., 11.,
       30., 30.,  0., 30., 30., 21., 15., 24.,  7., 20., 28.,  0.,  1.,
        1., 30., 30., 30., 30., 30., 30., 30., 30., 29., 25., 16., 30.])

In [ ]:
inds = hits.argsort()[-5:][::-1]
inds

array([51, 16, 19,  9,  7])

In [ ]:
ser =  X.columns
features = ser[inds]
features

Index(['Entropy_A_max', 'AR3_max', 'hjorth_complexity', 'AR1_min',
       'first_diff_max'],
      dtype='object')

In [ ]:
new_X = select_columns(X,features)
new_X.head()

Entropy_A_max   AR3_max  hjorth_complexity   AR1_min  first_diff_max
8881    4.976220e+06 -0.067859           2.070994 -1.825564       31.201944
6980    6.130247e+06 -0.126595           1.535197 -1.397677       32.440508
18773   5.510635e+06 -0.255201           1.595434 -1.241512       31.944456
7138    3.156649e+06 -0.236398           1.631120 -1.276469       21.449215
5543    2.416832e+05 -0.228626           1.630877 -1.636695       15.332635

In [ ]:
# Checking new accuracy with reduced 32 features
run_model(new_X,y)

(13067, 5) (13067,)


0.6037560862508695

# BorutaPy Module

In [ ]:
!pip install boruta

In [ ]:
from boruta import BorutaPy
from sklearn.ensemble import RandomForestClassifier
import numpy as np
###initialize Boruta
forest = RandomForestClassifier(
   n_jobs = -1, 
   max_depth = 5
)
boruta = BorutaPy(
   estimator = forest, 
   n_estimators = 'auto',
   max_iter = 20 # number of trials to perform
)
### fit Boruta (it accepts np.array, not pd.DataFrame)
boruta.fit(np.array(X), y)
### print results
green_area = X.columns[boruta.support_].to_list()
blue_area = X.columns[boruta.support_weak_].to_list()
print('features in the green area:', green_area)
print('features in the blue area:', blue_area)

features in the green area: ['fractal_dimension', 'kurtosis', 'secDiffMean', 'secDiffMax', 'skewness', 'first_diff_mean', 'first_diff_max', 'AR1_max', 'AR2_mean', 'AR2_max', 'AR3_mean', 'AR3_min', 'AR3_max', 'hjorth_activity', 'hjorth_complexity', 'PMax4', 'PRatio3', 'PRatio4', 'cA_mean_min', 'cA_mean_max', 'cA_std_max', 'cA_Energy_max', 'cD_std_mean', 'cD_std_min', 'cD_std_max', 'cD_Energy_mean', 'cD_Energy_min', 'cD_Energy_max', 'Entropy_D_mean', 'Entropy_D_min', 'Entropy_D_max', 'Entropy_A_max']
features in the blue area: ['AR1_mean', 'AR1_min', 'hjorth_mobility', 'PRatio2', 'cA_std_mean', 'cA_std_min', 'cA_Energy_mean', 'cA_Energy_min', 'Entropy_A_mean', 'Entropy_A_min']


In [ ]:
len(green_area) # got 32 features on 20 iterations, can further select top 5 or 4 on increasing  iterations

32

In [ ]:
feat = boruta.support_
feat

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False, False, False,  True, False, False,  True,
        True, False,  True,  True, False, False,  True, False, False,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True])

In [ ]:
ind = np.where(feat==1)
ind

(array([ 1,  2,  3,  4,  5,  6,  7, 10, 11, 13, 14, 15, 16, 17, 19, 23, 26,
        27, 29, 30, 33, 36, 40, 41, 42, 43, 44, 45, 46, 47, 48, 51]),)

In [ ]:
ser =  X.columns
features = ser[ind]
features

Index(['fractal_dimension', 'kurtosis', 'secDiffMean', 'secDiffMax',
       'skewness', 'first_diff_mean', 'first_diff_max', 'AR1_max', 'AR2_mean',
       'AR2_max', 'AR3_mean', 'AR3_min', 'AR3_max', 'hjorth_activity',
       'hjorth_complexity', 'PMax4', 'PRatio3', 'PRatio4', 'cA_mean_min',
       'cA_mean_max', 'cA_std_max', 'cA_Energy_max', 'cD_std_mean',
       'cD_std_min', 'cD_std_max', 'cD_Energy_mean', 'cD_Energy_min',
       'cD_Energy_max', 'Entropy_D_mean', 'Entropy_D_min', 'Entropy_D_max',
       'Entropy_A_max'],
      dtype='object')

In [ ]:
new_X = select_columns(X,features)
new_X.head()

fractal_dimension  kurtosis  ...  Entropy_D_max  Entropy_A_max
8881            1.964181  2.400335  ...   3.930293e+04   4.976220e+06
6980            1.991463  0.146082  ...   8.042087e+05   6.130247e+06
18773           1.997740  1.930806  ...   1.151290e+06   5.510635e+06
7138            1.990888  0.080560  ...   3.040354e+05   3.156649e+06
5543            1.983340  0.216440  ...   8.086052e+04   2.416832e+05

[5 rows x 32 columns]

In [ ]:
run_model(new_X,y)   # accuracy decreases to 64.85%

(13067, 32) (13067,)


0.6485045212149316

In [ ]:
boruta.n_features_

32

In [ ]:
boruta.ranking_   # bet feature has rank 1

array([ 8,  1,  1,  1,  1,  1,  1,  1,  2,  2,  1,  1,  3,  1,  1,  1,  1,
        1,  2,  1,  4,  6,  3,  1,  9,  2,  1,  1, 11,  1,  1,  2,  2,  1,
        2,  2,  1, 11,  5,  7,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,
        1])

# 2. Lasso Regularisation

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SelectFromModel
sel_ = SelectFromModel(LogisticRegression(C=1, penalty='l1',solver='liblinear'),max_features = 10) 

In [ ]:
sel_.fit(X, y)

/usr/local/lib/python3.6/dist-packages/sklearn/svm/_base.py:947: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


SelectFromModel(estimator=LogisticRegression(C=1, class_weight=None, dual=False,
                                             fit_intercept=True,
                                             intercept_scaling=1, l1_ratio=None,
                                             max_iter=100, multi_class='auto',
                                             n_jobs=None, penalty='l1',
                                             random_state=None,
                                             solver='liblinear', tol=0.0001,
                                             verbose=0, warm_start=False),
                max_features=10, norm_order=1, prefit=False, threshold=None)

In [ ]:
sel_.get_support()

array([False,  True, False, False, False,  True, False, False, False,
       False,  True, False,  True,  True, False,  True,  True, False,
        True,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False])

In [ ]:
selected_feat = X.columns[(sel_.get_support())]
selected_feat

Index(['fractal_dimension', 'skewness', 'AR1_max', 'AR2_min', 'AR2_max',
       'AR3_min', 'AR3_max', 'hjorth_mobility', 'hjorth_complexity',
       'cD_std_min'],
      dtype='object')

In [ ]:
new_X = select_columns(X,selected_feat)
new_X.shape

(13067, 10)

In [ ]:
#running model for reduced 38 features
run_model(new_X,y)  # Accuracy = 61.92% - 10 features , 61.2%  for 5 featuers

(13067, 10) (13067,)


0.6121029445861349

# 3. Recursive Feature Elimination

In [ ]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
#from sklearn.linear_model import LogisticRegression
model = RandomForestClassifier()
#model = LogisticRegression()

In [ ]:
selector = RFE(model,n_features_to_select=10, step=1)
selector.fit(X,y)

RFE(estimator=RandomForestClassifier(bootstrap=True, ccp_alpha=0.0,
                                     class_weight=None, criterion='gini',
                                     max_depth=None, max_features='auto',
                                     max_leaf_nodes=None, max_samples=None,
                                     min_impurity_decrease=0.0,
                                     min_impurity_split=None,
                                     min_samples_leaf=1, min_samples_split=2,
                                     min_weight_fraction_leaf=0.0,
                                     n_estimators=100, n_jobs=None,
                                     oob_score=False, random_state=None,
                                     verbose=0, warm_start=False),
    n_features_to_select=10, step=1, verbose=0)

In [ ]:
selector.support_

array([False, False,  True,  True, False, False, False, False, False,
       False, False,  True, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False,  True])

In [ ]:
selector.ranking_

array([14, 19,  1,  1,  7,  4, 22, 28, 33, 17,  6,  1, 10,  9,  8,  1,  2,
       40, 37, 16, 26, 34, 23,  5, 11, 25, 13,  3, 43,  1,  1, 36,  1, 38,
       39, 24, 31, 42, 15, 20, 18, 27, 29, 35, 12,  1, 30,  1, 21, 41, 32,
        1])

In [ ]:
selected_feat = X.columns[(selector.get_support())]
selected_feat

Index(['kurtosis', 'secDiffMean', 'AR2_mean', 'AR3_min', 'cA_mean_min',
       'cA_mean_max', 'cA_std_min', 'cD_Energy_max', 'Entropy_D_min',
       'Entropy_A_max'],
      dtype='object')

In [ ]:
selected_feat.shape

(10,)

In [ ]:
new_X = select_columns(X,selected_feat)
new_X.head()

kurtosis  secDiffMean  ...  Entropy_D_min  Entropy_A_max
8881   2.400335     3.488320  ...     227.663816   4.976220e+06
6980   0.146082     6.475594  ...    1814.660940   6.130247e+06
18773  1.930806     5.854897  ...    1123.675372   5.510635e+06
7138   0.080560     4.225086  ...     651.870449   3.156649e+06
5543   0.216440     2.987443  ...     681.426587   2.416832e+05

[5 rows x 10 columns]

In [ ]:
run_model(new_X,y)  # accuracy with 10 feautres - 54.97% with logistic regression
                    # ''       ''     '''       - 62.03% with random forest

(13067, 10) (13067,)


0.6422443774634825

# 4. Forward Slection , Backward Selection and Floating Selection

In [ ]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs
from sklearn.ensemble import RandomForestClassifier

In [ ]:
clf = RandomForestClassifier(n_estimators=100, n_jobs=-1)
sfs1 = sfs(clf,
           k_features=10,   # 5 features to select
           forward=True,   # forward seelction
           floating=True,  #  floating algorithm
           verbose=2,
           scoring='accuracy',
           cv=0)

sfs1.fit(np.array(X), y)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    4.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  52 out of  52 | elapsed:  2.9min finished

[2021-01-11 15:53:13] Features: 1/10 -- score: 0.9999234713400168[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.8s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  51 out of  51 | elapsed:  2.3min finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    3.2s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    6.6s finished

[2021-01-11 15:55:40] Features: 2/10 -- score: 1.0[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.3s remaining:    0.0s
[Parallel(n_jobs=1)]: Done  5

SequentialFeatureSelector(clone_estimator=True, cv=0,
                          estimator=RandomForestClassifier(bootstrap=True,
                                                           ccp_alpha=0.0,
                                                           class_weight=None,
                                                           criterion='gini',
                                                           max_depth=None,
                                                           max_features='auto',
                                                           max_leaf_nodes=None,
                                                           max_samples=None,
                                                           min_impurity_decrease=0.0,
                                                           min_impurity_split=None,
                                                           min_samples_leaf=1,
                                                           min_samples_split=2,
 

In [ ]:
features = sfs1.k_feature_names_
features

('0', '1', '2', '3', '4', '5', '6', '7', '8', '17')

In [ ]:
type(features)
features = np.array(features)
type(features)
features

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '17'], dtype='<U2')

In [ ]:
fet = X.columns
features = fet[[0, 1, 2, 3, 4, 5, 6, 7, 8, 17]]

In [ ]:
new_X = sfs1.transform(X)
new_X

array([[-6.53237235e+02,  1.96418117e+00,  2.40033548e+00, ...,
         3.12019437e+01, -1.48580392e+00,  2.76280952e+02],
       [ 7.22155134e+01,  1.99146307e+00,  1.46081879e-01, ...,
         3.24405077e+01, -1.12132620e+00,  2.00432253e+02],
       [ 5.10803327e+01,  1.99773990e+00,  1.93080627e+00, ...,
         3.19444555e+01, -1.00123055e+00,  1.59776557e+02],
       ...,
       [ 1.10783215e+01,  1.98567677e+00,  4.16489521e+00, ...,
         3.85185939e+01, -1.19578639e+00,  1.41586162e+02],
       [ 1.94967672e+01,  2.00000000e+00,  3.61215596e+00, ...,
         1.43008696e+02, -6.12740151e-01,  9.36732574e+02],
       [ 1.70393472e+02,  1.96418117e+00,  4.45192692e+00, ...,
         4.98121959e+01, -1.44603589e+00,  8.37361900e+02]])

In [ ]:
new_X = select_columns(X,features)
new_X

coeff_var  fractal_dimension  ...  AR1_mean  hjorth_activity
8881  -653.237235           1.964181  ... -1.485804       276.280952
6980    72.215513           1.991463  ... -1.121326       200.432253
18773   51.080333           1.997740  ... -1.001231       159.776557
7138     5.678293           1.990888  ... -1.117643        99.535873
5543   -48.459438           1.983340  ... -1.238982        43.549299
...           ...                ...  ...       ...              ...
15244  -13.939699           1.992611  ... -0.894432       593.827624
20120    4.421657           1.997740  ... -1.321971       422.836659
22062   11.078321           1.985677  ... -1.195786       141.586162
15084   19.496767           2.000000  ... -0.612740       936.732574
23279  170.393472           1.964181  ... -1.446036       837.361900

[13067 rows x 10 columns]

In [ ]:
run_model(new_X,y)

(13067, 10) (13067,)


0.605147229306747

# 5.Feature Importances

In [ ]:
model = RandomForestClassifier()

In [ ]:
model.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
importance = model.feature_importances_
importance

array([0.02161142, 0.02114718, 0.02331673, 0.02032807, 0.02046318,
       0.02380236, 0.01875688, 0.01970721, 0.01773187, 0.02123473,
       0.02384034, 0.02293024, 0.02307355, 0.02219219, 0.02227672,
       0.02326873, 0.0224629 , 0.01499219, 0.01689148, 0.0194063 ,
       0.01934999, 0.01723505, 0.0190162 , 0.02150717, 0.02031917,
       0.02049986, 0.02021597, 0.02132534, 0.        , 0.02727975,
       0.0256286 , 0.01546887, 0.01932593, 0.01609091, 0.01401746,
       0.01900071, 0.01602851, 0.        , 0.0221865 , 0.02115094,
       0.01805161, 0.02110921, 0.01895437, 0.01742516, 0.02068776,
       0.01920461, 0.01808754, 0.02171138, 0.01912538, 0.01423502,
       0.0190636 , 0.01726315])

In [ ]:
important_features_dict = {}

In [ ]:
for x,i in enumerate(importance):
	important_features_dict[x]=i
#important_features_dict

In [ ]:
important_features_list = sorted(important_features_dict,
                                 key=important_features_dict.get,
                                 reverse=True)
ind = important_features_list[0:10]
features = X.columns[ind]

In [ ]:
new_X = select_columns(X,features)
new_X.head()

cA_mean_min  cA_mean_max   AR1_max  ...  AR2_mean   AR3_max  AR3_mean
8881     -0.338424     0.281975 -1.117763  ...  0.867705 -0.067859 -0.219140
6980     -0.374439     1.168590 -0.942250  ...  0.766844 -0.126595 -0.315433
18773    -0.209973     0.211900 -0.753450  ...  0.702532 -0.255201 -0.422893
7138     -2.299335     1.270020 -0.967461  ...  0.713220 -0.236398 -0.290859
5543     -0.561133     0.796584 -0.654078  ...  0.838639 -0.228626 -0.320774

[5 rows x 10 columns]

In [ ]:
run_model(new_X,y)

(13067, 10) (13067,)


0.6232320890331555

# 6. Genetic Algorithm

In [ ]:
pip install sklearn-genetic


     |████████████████████████████████| 163kB 6.1MB/s 


In [ ]:
from genetic_selection import GeneticSelectionCV

In [ ]:
estimator = RandomForestClassifier()

In [ ]:
selector = GeneticSelectionCV(estimator,
                                  cv=5,
                                  verbose=1,
                                  scoring="accuracy",
                                  max_features=20,
                                  n_population=50,
                                  crossover_proba=0.5,
                                  mutation_proba=0.2,
                                  n_generations=40,
                                  crossover_independent_proba=0.5,
                                  mutation_independent_proba=0.05,
                                  tournament_size=3,
                                  n_gen_no_change=10,
                                  caching=True,
                                  n_jobs=-1)
selector = selector.fit(X, y)


Selecting features with genetic algorithm.
gen	nevals	avg                      	std                    	min                    	max                      
0  	50    	[ 0.60329028 11.28      ]	[0.0333776  6.55756052]	[0.52345652 1.        ]	[ 0.63863137 20.        ]
1  	21    	[-1199.44864189    16.38      ]	[3249.81896434    4.11771781]	[-1.e+04  7.e+00]      	[ 0.64199771 22.        ]
2  	32    	[-999.43022316   17.98      ]  	[3.00018993e+03 2.49391259e+00]	[-10000.     11.]      	[ 0.6518701 22.       ]  
3  	37    	[-1599.46503911    18.16      ]	[3.66629403e+03 2.67850705e+00]	[-10000.     13.]      	[ 0.65271257 24.        ]
4  	37    	[-1399.44911492    17.8       ]	[3.47009258e+03 2.34093998e+00]	[-10000.     14.]      	[ 0.65301824 24.        ]
5  	33    	[-799.40755693   17.64      ]  	[2.71310670e+03 1.93659495e+00]	[-10000.     14.]      	[ 0.65669147 22.        ]
6  	31    	[-399.37833999   17.58      ]  	[1.95971869e+03 1.90882163e+00]	[-10000.     12.]      	[ 0.6568449 2

In [ ]:
selected_feat = X.columns[(selector.get_support())]
selected_feat

Index(['cA_std_max', 'cD_std_mean', 'Entropy_D_min', 'Entropy_D_max',
       'Entropy_A_min'],
      dtype='object')

In [ ]:
new_X = select_columns(X,selected_feat)
new_X.head()

cA_std_max  cD_std_mean  Entropy_D_min  Entropy_D_max  Entropy_A_min
8881    52.508775     3.072807     227.663816   3.930293e+04   11338.150744
6980    59.526683     5.774239    1814.660940   8.042087e+05   59010.240385
18773   56.401663     5.802550    1123.675372   1.151290e+06   18411.365526
7138    44.192757     3.981972     651.870449   3.040354e+05   16805.100603
5543    14.396807     2.876462     681.426587   8.086052e+04   26252.581305

In [ ]:
run_model(X,y)

(13067, 52) (13067,)


0.651750521678646

In [ ]:
run_model(new_X,y)  

(13067, 5) (13067,)


0.6042198006028286